version: '3.8'

services:
  hugo-site:
    build: .
    ports:
      - "8080:80"
    volumes:
      # Mount the public directory for live updates (optional)
      - ./website/public:/usr/share/nginx/html
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
