name: S3-CI
run-name: Deploying to S3
on:
  push:
    branches: [ "main" ]
    paths:
      - "website/out/**"
      - ".github/workflows/deploy-to-s3.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: cd website && npm install

      - name: Build website
        run: cd website && npm run build
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROOT_ROLE_ARN }}
          role-session-name: github-actions-s3-sync
          aws-region: eu-west-1
      
      - name: Deploy to S3
        run: aws s3 sync website/out s3://milad.cloud --delete --acl public-read
      
      - name: Upload toolbelt
        run: |
          aws s3 cp website/toolbelt s3://milad.cloud/toolbelt \
          --acl public-read \
          --cache-control "no-cache" \
          --website-redirect "https://raw.githubusercontent.com/miladbeigi/portable-toolbelt/main/boot.sh"
