name: S3-CI
run-name: Deploying to S3
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROOT_ROLE_ARN }}
          role-session-name: github-actions-s3-sync
          aws-region: eu-west-1
      
      - name: Deploy to S3
        run: aws s3 sync website/out s3://milad.cloud --delete --acl public-read